resources:
- idgenerator.yaml

generatorOptions:
  disableNameSuffixHash: true

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: idgenerator
  newName: harbor.act.buaa.edu.cn/jiayuke/idgenerator
  newTag: v0.1.0
