// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: proto/id_generator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IdGeneratorClient is the client API for IdGenerator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IdGeneratorClient interface {
	GenerateId(ctx context.Context, in *GenerateIdRequest, opts ...grpc.CallOption) (*GenerateIdResponse, error)
}

type idGeneratorClient struct {
	cc grpc.ClientConnInterface
}

func NewIdGeneratorClient(cc grpc.ClientConnInterface) IdGeneratorClient {
	return &idGeneratorClient{cc}
}

func (c *idGeneratorClient) GenerateId(ctx context.Context, in *GenerateIdRequest, opts ...grpc.CallOption) (*GenerateIdResponse, error) {
	out := new(GenerateIdResponse)
	err := c.cc.Invoke(ctx, "/proto.IdGenerator/GenerateId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdGeneratorServer is the server API for IdGenerator service.
// All implementations must embed UnimplementedIdGeneratorServer
// for forward compatibility
type IdGeneratorServer interface {
	GenerateId(context.Context, *GenerateIdRequest) (*GenerateIdResponse, error)
	mustEmbedUnimplementedIdGeneratorServer()
}

// UnimplementedIdGeneratorServer must be embedded to have forward compatible implementations.
type UnimplementedIdGeneratorServer struct {
}

func (UnimplementedIdGeneratorServer) GenerateId(context.Context, *GenerateIdRequest) (*GenerateIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateId not implemented")
}
func (UnimplementedIdGeneratorServer) mustEmbedUnimplementedIdGeneratorServer() {}

// UnsafeIdGeneratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdGeneratorServer will
// result in compilation errors.
type UnsafeIdGeneratorServer interface {
	mustEmbedUnimplementedIdGeneratorServer()
}

func RegisterIdGeneratorServer(s grpc.ServiceRegistrar, srv IdGeneratorServer) {
	s.RegisterService(&IdGenerator_ServiceDesc, srv)
}

func _IdGenerator_GenerateId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdGeneratorServer).GenerateId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.IdGenerator/GenerateId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdGeneratorServer).GenerateId(ctx, req.(*GenerateIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdGenerator_ServiceDesc is the grpc.ServiceDesc for IdGenerator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdGenerator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.IdGenerator",
	HandlerType: (*IdGeneratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateId",
			Handler:    _IdGenerator_GenerateId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/id_generator.proto",
}
