// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.21.1
// source: proto/rpc_proxy.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcMsgRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SvcMeth string `protobuf:"bytes,2,opt,name=svc_meth,json=svcMeth,proto3" json:"svc_meth,omitempty"`
	Msg     []byte `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *RpcMsgRequest) Reset() {
	*x = RpcMsgRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcMsgRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcMsgRequest) ProtoMessage() {}

func (x *RpcMsgRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcMsgRequest.ProtoReflect.Descriptor instead.
func (*RpcMsgRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *RpcMsgRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RpcMsgRequest) GetSvcMeth() string {
	if x != nil {
		return x.SvcMeth
	}
	return ""
}

func (x *RpcMsgRequest) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

type RpcMsgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ok bool   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *RpcMsgResponse) Reset() {
	*x = RpcMsgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_proxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RpcMsgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcMsgResponse) ProtoMessage() {}

func (x *RpcMsgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcMsgResponse.ProtoReflect.Descriptor instead.
func (*RpcMsgResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *RpcMsgResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RpcMsgResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_rpc_proxy_proto protoreflect.FileDescriptor

var file_proto_rpc_proxy_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4c,
	0x0a, 0x0d, 0x52, 0x70, 0x63, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x73, 0x76, 0x63, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x73, 0x76, 0x63, 0x4d, 0x65, 0x74, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x30, 0x0a, 0x0e,
	0x52, 0x70, 0x63, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x32, 0x8c,
	0x01, 0x0a, 0x09, 0x52, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x3e, 0x0a, 0x0d,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x70, 0x63, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x70, 0x63, 0x4d,
	0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0e,
	0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x70, 0x63, 0x4d, 0x73, 0x67, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x70, 0x63,
	0x4d, 0x73, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_rpc_proxy_proto_rawDescOnce sync.Once
	file_proto_rpc_proxy_proto_rawDescData = file_proto_rpc_proxy_proto_rawDesc
)

func file_proto_rpc_proxy_proto_rawDescGZIP() []byte {
	file_proto_rpc_proxy_proto_rawDescOnce.Do(func() {
		file_proto_rpc_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_rpc_proxy_proto_rawDescData)
	})
	return file_proto_rpc_proxy_proto_rawDescData
}

var file_proto_rpc_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_rpc_proxy_proto_goTypes = []interface{}{
	(*RpcMsgRequest)(nil),  // 0: proto.RpcMsgRequest
	(*RpcMsgResponse)(nil), // 1: proto.RpcMsgResponse
}
var file_proto_rpc_proxy_proto_depIdxs = []int32{
	0, // 0: proto.RpcServer.HandleRequest:input_type -> proto.RpcMsgRequest
	0, // 1: proto.RpcServer.HandleResponse:input_type -> proto.RpcMsgRequest
	1, // 2: proto.RpcServer.HandleRequest:output_type -> proto.RpcMsgResponse
	1, // 3: proto.RpcServer.HandleResponse:output_type -> proto.RpcMsgResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_rpc_proxy_proto_init() }
func file_proto_rpc_proxy_proto_init() {
	if File_proto_rpc_proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_rpc_proxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcMsgRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_proxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RpcMsgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_rpc_proxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rpc_proxy_proto_goTypes,
		DependencyIndexes: file_proto_rpc_proxy_proto_depIdxs,
		MessageInfos:      file_proto_rpc_proxy_proto_msgTypes,
	}.Build()
	File_proto_rpc_proxy_proto = out.File
	file_proto_rpc_proxy_proto_rawDesc = nil
	file_proto_rpc_proxy_proto_goTypes = nil
	file_proto_rpc_proxy_proto_depIdxs = nil
}
