// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        (unknown)
// source: proto/rpc_proxy.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AsyncCallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Source   string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Target   string `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Seq      int32  `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"`
	Callback string `protobuf:"bytes,5,opt,name=callback,proto3" json:"callback,omitempty"`
	Msg      []byte `protobuf:"bytes,6,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *AsyncCallRequest) Reset() {
	*x = AsyncCallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_proxy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AsyncCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncCallRequest) ProtoMessage() {}

func (x *AsyncCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proxy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncCallRequest.ProtoReflect.Descriptor instead.
func (*AsyncCallRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proxy_proto_rawDescGZIP(), []int{0}
}

func (x *AsyncCallRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AsyncCallRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AsyncCallRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *AsyncCallRequest) GetSeq() int32 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *AsyncCallRequest) GetCallback() string {
	if x != nil {
		return x.Callback
	}
	return ""
}

func (x *AsyncCallRequest) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

type AsyncCallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ok bool  `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *AsyncCallResponse) Reset() {
	*x = AsyncCallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_proxy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AsyncCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AsyncCallResponse) ProtoMessage() {}

func (x *AsyncCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proxy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AsyncCallResponse.ProtoReflect.Descriptor instead.
func (*AsyncCallResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proxy_proto_rawDescGZIP(), []int{1}
}

func (x *AsyncCallResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AsyncCallResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type InitSyncCallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Msg    []byte `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *InitSyncCallRequest) Reset() {
	*x = InitSyncCallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_proxy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitSyncCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSyncCallRequest) ProtoMessage() {}

func (x *InitSyncCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proxy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSyncCallRequest.ProtoReflect.Descriptor instead.
func (*InitSyncCallRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proxy_proto_rawDescGZIP(), []int{2}
}

func (x *InitSyncCallRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *InitSyncCallRequest) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

type InitSyncCallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool  `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Id int64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *InitSyncCallResponse) Reset() {
	*x = InitSyncCallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_proxy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitSyncCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSyncCallResponse) ProtoMessage() {}

func (x *InitSyncCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proxy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSyncCallResponse.ProtoReflect.Descriptor instead.
func (*InitSyncCallResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proxy_proto_rawDescGZIP(), []int{3}
}

func (x *InitSyncCallResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *InitSyncCallResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SyncCallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *SyncCallRequest) Reset() {
	*x = SyncCallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_proxy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCallRequest) ProtoMessage() {}

func (x *SyncCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proxy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCallRequest.ProtoReflect.Descriptor instead.
func (*SyncCallRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proxy_proto_rawDescGZIP(), []int{4}
}

func (x *SyncCallRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SyncCallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok  bool   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Msg []byte `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SyncCallResponse) Reset() {
	*x = SyncCallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_proxy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncCallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncCallResponse) ProtoMessage() {}

func (x *SyncCallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proxy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncCallResponse.ProtoReflect.Descriptor instead.
func (*SyncCallResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proxy_proto_rawDescGZIP(), []int{5}
}

func (x *SyncCallResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SyncCallResponse) GetMsg() []byte {
	if x != nil {
		return x.Msg
	}
	return nil
}

type InitCheckpointRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Target string `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *InitCheckpointRequest) Reset() {
	*x = InitCheckpointRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_proxy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitCheckpointRequest) ProtoMessage() {}

func (x *InitCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proxy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitCheckpointRequest.ProtoReflect.Descriptor instead.
func (*InitCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proxy_proto_rawDescGZIP(), []int{6}
}

func (x *InitCheckpointRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *InitCheckpointRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type InitCheckpointResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ok bool  `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *InitCheckpointResponse) Reset() {
	*x = InitCheckpointResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_proxy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InitCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitCheckpointResponse) ProtoMessage() {}

func (x *InitCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proxy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitCheckpointResponse.ProtoReflect.Descriptor instead.
func (*InitCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proxy_proto_rawDescGZIP(), []int{7}
}

func (x *InitCheckpointResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *InitCheckpointResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type WaitCheckpointRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *WaitCheckpointRequest) Reset() {
	*x = WaitCheckpointRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_proxy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitCheckpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitCheckpointRequest) ProtoMessage() {}

func (x *WaitCheckpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proxy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitCheckpointRequest.ProtoReflect.Descriptor instead.
func (*WaitCheckpointRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proxy_proto_rawDescGZIP(), []int{8}
}

func (x *WaitCheckpointRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type WaitCheckpointResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *WaitCheckpointResponse) Reset() {
	*x = WaitCheckpointResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_proxy_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WaitCheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WaitCheckpointResponse) ProtoMessage() {}

func (x *WaitCheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proxy_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WaitCheckpointResponse.ProtoReflect.Descriptor instead.
func (*WaitCheckpointResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proxy_proto_rawDescGZIP(), []int{9}
}

func (x *WaitCheckpointResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type SendBarrierRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Target string `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *SendBarrierRequest) Reset() {
	*x = SendBarrierRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_proxy_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBarrierRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBarrierRequest) ProtoMessage() {}

func (x *SendBarrierRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proxy_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBarrierRequest.ProtoReflect.Descriptor instead.
func (*SendBarrierRequest) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proxy_proto_rawDescGZIP(), []int{10}
}

func (x *SendBarrierRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SendBarrierRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *SendBarrierRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type SendBarrierResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *SendBarrierResponse) Reset() {
	*x = SendBarrierResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_rpc_proxy_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBarrierResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBarrierResponse) ProtoMessage() {}

func (x *SendBarrierResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rpc_proxy_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBarrierResponse.ProtoReflect.Descriptor instead.
func (*SendBarrierResponse) Descriptor() ([]byte, []int) {
	return file_proto_rpc_proxy_proto_rawDescGZIP(), []int{11}
}

func (x *SendBarrierResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_proto_rpc_proxy_proto protoreflect.FileDescriptor

var file_proto_rpc_proxy_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x78,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92,
	0x01, 0x0a, 0x10, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x73, 0x65, 0x71, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63,
	0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63,
	0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x33, 0x0a, 0x11, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x43, 0x61, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x3f, 0x0a, 0x13, 0x49, 0x6e, 0x69, 0x74,
	0x53, 0x79, 0x6e, 0x63, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x36, 0x0a, 0x14, 0x49, 0x6e, 0x69,
	0x74, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f,
	0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x21, 0x0a, 0x0f, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x34, 0x0a, 0x10, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x61, 0x6c, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x47, 0x0a, 0x15, 0x49, 0x6e,
	0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x22, 0x38, 0x0a, 0x16, 0x49, 0x6e, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x27, 0x0a,
	0x15, 0x57, 0x61, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x16, 0x57, 0x61, 0x69, 0x74, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x22, 0x54, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22, 0x25, 0x0a, 0x13, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x61,
	0x72, 0x72, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x32, 0xc0, 0x03,
	0x0a, 0x08, 0x52, 0x70, 0x63, 0x50, 0x72, 0x6f, 0x78, 0x79, 0x12, 0x40, 0x0a, 0x09, 0x41, 0x73,
	0x79, 0x6e, 0x63, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x41, 0x73, 0x79, 0x6e, 0x63, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x73, 0x79, 0x6e, 0x63, 0x43, 0x61,
	0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0c,
	0x49, 0x6e, 0x69, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x1a, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x69, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x61, 0x6c,
	0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x49, 0x6e, 0x69, 0x74, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x43,
	0x61, 0x6c, 0x6c, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x79, 0x6e, 0x63,
	0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0e, 0x49, 0x6e, 0x69, 0x74, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x49, 0x6e, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49,
	0x6e, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4f, 0x0a, 0x0e, 0x57, 0x61, 0x69, 0x74, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x57, 0x61, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x57, 0x61, 0x69, 0x74, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64,
	0x42, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x12, 0x19, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x65, 0x6e, 0x64, 0x42, 0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42,
	0x61, 0x72, 0x72, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_proto_rpc_proxy_proto_rawDescOnce sync.Once
	file_proto_rpc_proxy_proto_rawDescData = file_proto_rpc_proxy_proto_rawDesc
)

func file_proto_rpc_proxy_proto_rawDescGZIP() []byte {
	file_proto_rpc_proxy_proto_rawDescOnce.Do(func() {
		file_proto_rpc_proxy_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_rpc_proxy_proto_rawDescData)
	})
	return file_proto_rpc_proxy_proto_rawDescData
}

var file_proto_rpc_proxy_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_rpc_proxy_proto_goTypes = []interface{}{
	(*AsyncCallRequest)(nil),       // 0: proto.AsyncCallRequest
	(*AsyncCallResponse)(nil),      // 1: proto.AsyncCallResponse
	(*InitSyncCallRequest)(nil),    // 2: proto.InitSyncCallRequest
	(*InitSyncCallResponse)(nil),   // 3: proto.InitSyncCallResponse
	(*SyncCallRequest)(nil),        // 4: proto.SyncCallRequest
	(*SyncCallResponse)(nil),       // 5: proto.SyncCallResponse
	(*InitCheckpointRequest)(nil),  // 6: proto.InitCheckpointRequest
	(*InitCheckpointResponse)(nil), // 7: proto.InitCheckpointResponse
	(*WaitCheckpointRequest)(nil),  // 8: proto.WaitCheckpointRequest
	(*WaitCheckpointResponse)(nil), // 9: proto.WaitCheckpointResponse
	(*SendBarrierRequest)(nil),     // 10: proto.SendBarrierRequest
	(*SendBarrierResponse)(nil),    // 11: proto.SendBarrierResponse
}
var file_proto_rpc_proxy_proto_depIdxs = []int32{
	0,  // 0: proto.RpcProxy.AsyncCall:input_type -> proto.AsyncCallRequest
	2,  // 1: proto.RpcProxy.InitSyncCall:input_type -> proto.InitSyncCallRequest
	4,  // 2: proto.RpcProxy.SyncCall:input_type -> proto.SyncCallRequest
	6,  // 3: proto.RpcProxy.InitCheckpoint:input_type -> proto.InitCheckpointRequest
	8,  // 4: proto.RpcProxy.WaitCheckpoint:input_type -> proto.WaitCheckpointRequest
	10, // 5: proto.RpcProxy.SendBarrier:input_type -> proto.SendBarrierRequest
	1,  // 6: proto.RpcProxy.AsyncCall:output_type -> proto.AsyncCallResponse
	3,  // 7: proto.RpcProxy.InitSyncCall:output_type -> proto.InitSyncCallResponse
	5,  // 8: proto.RpcProxy.SyncCall:output_type -> proto.SyncCallResponse
	7,  // 9: proto.RpcProxy.InitCheckpoint:output_type -> proto.InitCheckpointResponse
	9,  // 10: proto.RpcProxy.WaitCheckpoint:output_type -> proto.WaitCheckpointResponse
	11, // 11: proto.RpcProxy.SendBarrier:output_type -> proto.SendBarrierResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_rpc_proxy_proto_init() }
func file_proto_rpc_proxy_proto_init() {
	if File_proto_rpc_proxy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_rpc_proxy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AsyncCallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_proxy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AsyncCallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_proxy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitSyncCallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_proxy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitSyncCallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_proxy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncCallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_proxy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncCallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_proxy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitCheckpointRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_proxy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InitCheckpointResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_proxy_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitCheckpointRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_proxy_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WaitCheckpointResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_proxy_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBarrierRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_rpc_proxy_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBarrierResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_rpc_proxy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rpc_proxy_proto_goTypes,
		DependencyIndexes: file_proto_rpc_proxy_proto_depIdxs,
		MessageInfos:      file_proto_rpc_proxy_proto_msgTypes,
	}.Build()
	File_proto_rpc_proxy_proto = out.File
	file_proto_rpc_proxy_proto_rawDesc = nil
	file_proto_rpc_proxy_proto_goTypes = nil
	file_proto_rpc_proxy_proto_depIdxs = nil
}
