// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.1
// source: proto/rpc_proxy.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RpcServerClient is the client API for RpcServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RpcServerClient interface {
	HandleRequest(ctx context.Context, in *RpcMsgRequest, opts ...grpc.CallOption) (*RpcMsgResponse, error)
	HandleResponse(ctx context.Context, in *RpcMsgRequest, opts ...grpc.CallOption) (*RpcMsgResponse, error)
}

type rpcServerClient struct {
	cc grpc.ClientConnInterface
}

func NewRpcServerClient(cc grpc.ClientConnInterface) RpcServerClient {
	return &rpcServerClient{cc}
}

func (c *rpcServerClient) HandleRequest(ctx context.Context, in *RpcMsgRequest, opts ...grpc.CallOption) (*RpcMsgResponse, error) {
	out := new(RpcMsgResponse)
	err := c.cc.Invoke(ctx, "/proto.RpcServer/HandleRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rpcServerClient) HandleResponse(ctx context.Context, in *RpcMsgRequest, opts ...grpc.CallOption) (*RpcMsgResponse, error) {
	out := new(RpcMsgResponse)
	err := c.cc.Invoke(ctx, "/proto.RpcServer/HandleResponse", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RpcServerServer is the server API for RpcServer service.
// All implementations must embed UnimplementedRpcServerServer
// for forward compatibility
type RpcServerServer interface {
	HandleRequest(context.Context, *RpcMsgRequest) (*RpcMsgResponse, error)
	HandleResponse(context.Context, *RpcMsgRequest) (*RpcMsgResponse, error)
	mustEmbedUnimplementedRpcServerServer()
}

// UnimplementedRpcServerServer must be embedded to have forward compatible implementations.
type UnimplementedRpcServerServer struct {
}

func (UnimplementedRpcServerServer) HandleRequest(context.Context, *RpcMsgRequest) (*RpcMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleRequest not implemented")
}
func (UnimplementedRpcServerServer) HandleResponse(context.Context, *RpcMsgRequest) (*RpcMsgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HandleResponse not implemented")
}
func (UnimplementedRpcServerServer) mustEmbedUnimplementedRpcServerServer() {}

// UnsafeRpcServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RpcServerServer will
// result in compilation errors.
type UnsafeRpcServerServer interface {
	mustEmbedUnimplementedRpcServerServer()
}

func RegisterRpcServerServer(s grpc.ServiceRegistrar, srv RpcServerServer) {
	s.RegisterService(&RpcServer_ServiceDesc, srv)
}

func _RpcServer_HandleRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServerServer).HandleRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RpcServer/HandleRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServerServer).HandleRequest(ctx, req.(*RpcMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RpcServer_HandleResponse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RpcMsgRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RpcServerServer).HandleResponse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RpcServer/HandleResponse",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RpcServerServer).HandleResponse(ctx, req.(*RpcMsgRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RpcServer_ServiceDesc is the grpc.ServiceDesc for RpcServer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RpcServer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RpcServer",
	HandlerType: (*RpcServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HandleRequest",
			Handler:    _RpcServer_HandleRequest_Handler,
		},
		{
			MethodName: "HandleResponse",
			Handler:    _RpcServer_HandleResponse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rpc_proxy.proto",
}
