apiVersion: msc.shiguojq.com/v1
kind: MicroService
metadata:
  name: servicea
  namespace: microsvc-controller-system
spec:
  image: harbor.act.buaa.edu.cn/jiayuke/example1-servicea:v0.1.0
  config:
    - name: "ID_GENERATOR_HOST"
      value: "microsvc-controller-idgenerator:8080"
    - name: "CHECKPOINT_MODE"
      value: "1"
  port: 8080
  startPoint: false

